# Generated by Django 3.1.6 on 2021-02-09 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50, unique=True)),
                ('current_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Closed')], default=1)),
            ],
        ),
    ]
