# Generated by Django 3.1.6 on 2021-02-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='current_amount',
            new_name='balance_amount',
        ),
    ]
