# Generated by Django 3.1.6 on 2021-02-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trasactions', '0002_auto_20210210_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
    ]
