# Generated by Django 3.1.6 on 2021-02-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasactions', '0008_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Successful'), (2, 'Failed'), (3, 'Processing')], default=3),
        ),
    ]
