# Generated by Django 3.1.6 on 2021-02-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210210_1443'),
        ('trasactions', '0009_auto_20210210_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='account.account'),
        ),
    ]
