# Generated by Django 3.1.6 on 2021-02-10 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trasactions', '0011_auto_20210210_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
