# Generated by Django 3.1.6 on 2021-02-10 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trasactions', '0012_transaction_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
